# Simulation Environment Configuration

environment:
  # Episode settings
  max_steps: 500
  render_width: 224
  render_height: 224
  fps: 10
  
  # Camera settings (capsule endoscope inside digestive system)
  fov: 70  # Field of view in degrees
  near_clip: 0.01
  far_clip: 10.0
  initial_position: [0.0, 0.0, 0.0]  # Start at CENTER (inside stomach)
  initial_rotation: [0.0, 0.0, 0.0]  # roll, pitch, yaw in radians
  
  # Action space (discrete) - increased for larger 5x scaled model
  actions:
    yaw_delta: 0.1  # radians
    pitch_delta: 0.1  # radians
    forward_delta: 0.15  # meters (3x faster for larger model)
    zoom_delta: 0.02
  
  # Lesion synthesis
  lesions_per_episode:
    min: 1
    max: 4
  lesion_size:
    min: 0.01  # meters
    max: 0.05
  lesion_color:
    base: [180, 50, 50]  # RGB, reddish-brown
    variation: 30
  
  # Domain randomization
  lighting:
    intensity_range: [0.5, 1.5]
    color_temp_range: [3000, 6500]  # Kelvin
  camera_noise:
    gaussian_std: 0.02
  texture_variation: true
  
  # Collision detection
  collision_threshold: 0.02  # Distance to surface in meters
  collision_normal_dot: 0.9  # Normal vector threshold
  
  # Coverage tracking
  coverage_grid_size: 32
  coverage_ray_samples: 100

# Reward function coefficients
reward:
  alpha: 0.5   # Coverage weight
  beta: 0.4    # CNN anomaly detection weight
  gamma: 0.2   # Collision penalty weight
  delta: 0.05  # Action jerk penalty weight
  
  # Specific rewards
  coverage_per_new_cell: 0.1
  anomaly_detection_bonus: 1.0
  collision_penalty: -0.5
  jerk_penalty_factor: -0.01
  episode_completion_bonus: 5.0

# Curriculum learning
curriculum:
  enabled: true
  stages:
    - name: "easy"
      episodes: 0
      difficulty:
        lumen_width: 0.15
        bend_complexity: 1.0
        lesions_per_episode: 1
    - name: "medium"
      episodes: 5000
      difficulty:
        lumen_width: 0.10
        bend_complexity: 1.5
        lesions_per_episode: 2
    - name: "hard"
      episodes: 15000
      difficulty:
        lumen_width: 0.08
        bend_complexity: 2.0
        lesions_per_episode: 4

# Rendering
rendering:
  offscreen: true
  ambient_light: 0.4
  directional_light: 0.8
  shadows: false  # Disable for speed
  antialiasing: false

